# NumPy arrays and basics

In [4]:
import numpy as np
import time

### arrays in numPy

In [2]:
# 1d array 
arr_1d = np.array([1,2,3,4,5,6])
print(arr_1d)

# 2d array
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

#3d array
arr_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr_3d)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


### List vs numPy array

In [7]:
# python list
py_list = [1,2,3]
print("Python list multiplication" , py_list * 2)

#numPy list
np_array = np.array([1,2,3])
print("numPy array multiplication" , np_array * 2)


# Time duration in big calculations
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("\n py_list calculation time period", time.time() - start)


start = time.time()
np_array = np.arange(10000000) * 2
print("\n np_array calculation time period", time.time() - start)




Python list multiplication [1, 2, 3, 1, 2, 3]
numPy array multiplication [2 4 6]

 py_list calculation time period 3.3272900581359863

 np_array calculation time period 0.5450193881988525


### creating arrays from scratch 

In [ ]:
# zeros metrics
zeros = np.zeros((3,4))
print(zeros, "\n")

# ones  metrics
ones = np.ones((4,4))
print(ones , "\n")

# constant metrics
constant = np.full((5,5),7)
print(constant, "\n")

# sequence metrics
sequence = np.arange(0, 20 , 3) # start , stop , skip
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]] 

[ 0  3  6  9 12 15 18]


### Array properties

In [13]:
arr = np.random.randint(20, size=(4,4)) 
print("shape" , arr.shape)
print("size" , arr.size)
print("dimension" , arr.ndim)
print("dtype" , arr.dtype)


shape (4, 4)
size 16
dimension 2
dtype int64


### Array reshaping

In [6]:
arr = np.arange(12)
print("original array \n", arr)

reshapedArray = arr.reshape((3,4))
print("reshaped array \n", reshapedArray) 

flattenArray = reshapedArray.flatten()
print("flatten array \n", flattenArray) # values base copy

ravelArray = reshapedArray.ravel()
print("reval array \n", ravelArray) # this is reference base  copy

transposeArray = reshapedArray.T
print("transpose array \n " , transposeArray)

original array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flatten array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
reval array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose array 
  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
