# NumPy Array Operations

In [1]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("basic slicing \n", arr[1:6]) # basic slicing 
print("step slicing \n", arr[0:7:2]) # start , stop , skip each number
print("negative slicing \n", arr[-5])

basic slicing 
 [2 3 4 5 6]
step slicing 
 [1 3 5 7]
negative slicing 
 6


In [11]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("row wise slicing \n", arr_2d[2,1]) # row index , row value index
print("full row slicing \n", arr_2d[0]) # enter row index
print("column slicing \n" , arr_2d[:,2])


row wise slicing 
 8
full row slicing 
 [1 2 3]
column slicing 
 [3 6 9]


### Filtration

In [13]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
odd_numbers = numbers[numbers % 2 != 0]
print("even numbers \n", even_numbers)
print("odd numbers \n", odd_numbers)


even numbers 
 [ 2  4  6  8 10]
odd numbers 
 [1 3 5 7 9]


### Mask slicing

In [14]:
mask = numbers > 5
print("mask slicing \n", numbers[mask])

mask slicing 
 [ 6  7  8  9 10]


### conditional array 

In [17]:
where = np.where(numbers > 5)
print("where \n", where )
print('list of number array on condition \n', numbers[where])



conditional_array = np.where(numbers > 4 , numbers * 5 , numbers) # if (condition) ? number * 4 : numbers
print("conditional array \n", conditional_array)



where 
 (array([5, 6, 7, 8, 9]),)
list of number array on condition 
 [ 6  7  8  9 10]
conditional array 
 [ 1  2  3  4 25 30 35 40 45 50]
